#!/usr/bin/env python3
"""Config file that contains a variety of information for our
web correct functioning.
"""

calculus_algorithms =  {"simple": {"fancy_name" : "Simple", "differentiate_gaps" : "Y"},
                        "all_vs_all": { "fancy_name" : "All vs All", "differentiate_gaps" : "Y"},
                        "all_vs_all_means": { "fancy_name" : "All vs All (Means)", "differentiate_gaps" : "Y"},
                        "whole_annotation_simple": { "fancy_name" : "Simple (Whole annotation)", "differentiate_gaps" : "N"},
                        "whole_annotation_all_vs_all": { "fancy_name" : "All vs All (Whole annotation)", "differentiate_gaps" : "N"},
                        "whole_annotation_all_vs_all_means": { "fancy_name" : "All vs All (Means + Whole annotation)", "differentiate_gaps" : "N"}}

feature_info = {"INIT_MET": {"fancy_name": "Initiator methionine"},
                "SIGNAL": {"fancy_name": "Signal sequence"},
                "PROPEP": {"fancy_name": "Propeptide"},
                "TRANSIT": {"fancy_name": "Transit peptide"},
                "CHAIN": {"fancy_name": "Polipeptide chain"},
                "PEPTIDE": {"fancy_name": "Released active peptide"},
                "TOPO_DOM": {"fancy_name": "Topological domain"},
                "TRANSMEM": {"fancy_name": "Transmembrane region"},
                "INTRAMEM": {"fancy_name": "Intramembrane region"},
                "DOMAIN": {"fancy_name": "Domain"},
                "REPEAT": {"fancy_name": "Internal sequence repetition"},
                "CA_BIND": {"fancy_name": "Calcium-binding region"},
                "ZN_FING": {"fancy_name": "Zinc finger region"},
                "DNA_BIND": {"fancy_name": "DNA-binding region"},
                "NP_BIND": {"fancy_name": "Nucleotide-binding region"},
                "REGION": {"fancy_name": "Region of interest"},
                "COILED": {"fancy_name": "Coiled-coil region"},
                "MOTIF": {"fancy_name": "Short sequence motif"},
                "COMPBIAS": {"fancy_name": "Compositional biased region"},
                "ACT_SITE": {"fancy_name": "Active site"},
                "METAL": {"fancy_name": "Metal ion binding site"},
                "BINDING": {"fancy_name": "Chemical group binding site"},
                "SITE": {"fancy_name": "Interesting single aminoacid site"},
                "NON_STD": {"fancy_name": "Non-standard aminoacid"},
                "MOD_RES": {"fancy_name": "Posttranslational modification"},
                "LIPID": {"fancy_name": "Covalent lipid binding"},
                "CARBOHYD": {"fancy_name": "Glycosylation site"},
                "DISULFID": {"fancy_name": "Disulfide bond"},
                "CROSSLINK": {"fancy_name": "Posttranslationally formed aa bonds"},
                "VAR_SEQ": {"fancy_name": "Sequence variants (known source)"},
                "VARIANT": {"fancy_name": "Sequence variants (unknown source)"},
                "MUTAGEN": {"fancy_name": "Experimentally mutated site"},
                "UNSURE": {"fancy_name": "Uncertain site"},
                "CONFLICT": {"fancy_name": "Site with info in conflict"},
                "NON_CONS": {"fancy_name": "Non-consecutive residues"},
                "NON_TER": {"fancy_name": "Non terminal residue"},
                "HELIX": {"fancy_name": "Secondary structure: Helix"},
                "STRAND": {"fancy_name": "Secondary structure: Strand"},
                "TURN": {"fancy_name": "Secondary structure: Turn"},
                "INIT_MET": {"fancy_name": "Initiator methionine"}}